package com.zaze.aarrepo.commons.download;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TDOWNLOAD".
 */
public class TDownload implements java.io.Serializable {

    private Long id;
    /**
     * 类型对应的id
     */
    private long down_id;
    /**
     * 下载类型(题库, 图片????)
     */
    private int down_type;
    /**
     * 下载状态
     */
    private int down_state;
    /**
     * 下载url
     */
    private String down_url;
    /**
     * 保存路径
     */
    private String save_path;
    /**
     * 安装
     */
    private String install_path;
    private String version;
    private String down_time;
    private String md5;

    public TDownload() {
    }

    public TDownload(Long id) {
        this.id = id;
    }

    public TDownload(Long id, long down_id, int down_type, int down_state, String down_url, String save_path, String install_path, String version, String down_time, String md5) {
        this.id = id;
        this.down_id = down_id;
        this.down_type = down_type;
        this.down_state = down_state;
        this.down_url = down_url;
        this.save_path = save_path;
        this.install_path = install_path;
        this.version = version;
        this.down_time = down_time;
        this.md5 = md5;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getDown_id() {
        return down_id;
    }

    public void setDown_id(long down_id) {
        this.down_id = down_id;
    }

    public int getDown_type() {
        return down_type;
    }

    public void setDown_type(int down_type) {
        this.down_type = down_type;
    }

    public int getDown_state() {
        return down_state;
    }

    public void setDown_state(int down_state) {
        this.down_state = down_state;
    }

    public String getDown_url() {
        return down_url;
    }

    public void setDown_url(String down_url) {
        this.down_url = down_url;
    }

    public String getSave_path() {
        return save_path;
    }

    public void setSave_path(String save_path) {
        this.save_path = save_path;
    }

    public String getInstall_path() {
        return install_path;
    }

    public void setInstall_path(String install_path) {
        this.install_path = install_path;
    }

    public String getVersion() {
        return version;
    }

    public void setVersion(String version) {
        this.version = version;
    }

    public String getDown_time() {
        return down_time;
    }

    public void setDown_time(String down_time) {
        this.down_time = down_time;
    }

    public String getMd5() {
        return md5;
    }

    public void setMd5(String md5) {
        this.md5 = md5;
    }

}
